name: alert-fee

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  alert-fee:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: alert-fee
        run: |
          DISCORD_BOT_TOKEN=${{secrets.DISCORD_BOT_TOKEN}} DISCORD_CHANNEL_ID=${{secrets.DISCORD_CHANNEL_ID}} node app.js
